//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pogodynka.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pogodynka.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbale to get device location..
        /// </summary>
        internal static string alertLocationMessage {
            get {
                return ResourceManager.GetString("alertLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string alertLocationTitle {
            get {
                return ResourceManager.GetString("alertLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location permissions.
        /// </summary>
        internal static string alertNoAccessMessage {
            get {
                return ResourceManager.GetString("alertNoAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        internal static string alertNoAccessTitle {
            get {
                return ResourceManager.GetString("alertNoAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place not found..
        /// </summary>
        internal static string alertNotFoundMessage {
            get {
                return ResourceManager.GetString("alertNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string alertNotFoundTitle {
            get {
                return ResourceManager.GetString("alertNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect with server..
        /// </summary>
        internal static string errorHttpMessage {
            get {
                return ResourceManager.GetString("errorHttpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hum: .
        /// </summary>
        internal static string labelHum {
            get {
                return ResourceManager.GetString("labelHum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string labelHumidity {
            get {
                return ResourceManager.GetString("labelHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre: .
        /// </summary>
        internal static string labelPre {
            get {
                return ResourceManager.GetString("labelPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string labelPressure {
            get {
                return ResourceManager.GetString("labelPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string labelSearch {
            get {
                return ResourceManager.GetString("labelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string labelTemperature {
            get {
                return ResourceManager.GetString("labelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: .
        /// </summary>
        internal static string labelTempMax {
            get {
                return ResourceManager.GetString("labelTempMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min: .
        /// </summary>
        internal static string labelTempMin {
            get {
                return ResourceManager.GetString("labelTempMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win: .
        /// </summary>
        internal static string labelWin {
            get {
                return ResourceManager.GetString("labelWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string labelWind {
            get {
                return ResourceManager.GetString("labelWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string labelWindDirect {
            get {
                return ResourceManager.GetString("labelWindDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir: .
        /// </summary>
        internal static string labelWinDir {
            get {
                return ResourceManager.GetString("labelWinDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string Weather_default {
            get {
                return ResourceManager.GetString("Weather_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sky.
        /// </summary>
        internal static string Weather_value_0 {
            get {
                return ResourceManager.GetString("Weather_value_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly clear.
        /// </summary>
        internal static string Weather_value_1 {
            get {
                return ResourceManager.GetString("Weather_value_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly cloudy.
        /// </summary>
        internal static string Weather_value_2 {
            get {
                return ResourceManager.GetString("Weather_value_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        internal static string Weather_value_3 {
            get {
                return ResourceManager.GetString("Weather_value_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string Weather_value_45 {
            get {
                return ResourceManager.GetString("Weather_value_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depositing rime fog.
        /// </summary>
        internal static string Weather_value_48 {
            get {
                return ResourceManager.GetString("Weather_value_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle: light.
        /// </summary>
        internal static string Weather_value_51 {
            get {
                return ResourceManager.GetString("Weather_value_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle: moderate.
        /// </summary>
        internal static string Weather_value_53 {
            get {
                return ResourceManager.GetString("Weather_value_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle: dense intensity.
        /// </summary>
        internal static string Weather_value_55 {
            get {
                return ResourceManager.GetString("Weather_value_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Drizzle: light.
        /// </summary>
        internal static string Weather_value_56 {
            get {
                return ResourceManager.GetString("Weather_value_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Drizzle: dense intensity.
        /// </summary>
        internal static string Weather_value_57 {
            get {
                return ResourceManager.GetString("Weather_value_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain: slight.
        /// </summary>
        internal static string Weather_value_61 {
            get {
                return ResourceManager.GetString("Weather_value_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain: moderate.
        /// </summary>
        internal static string Weather_value_63 {
            get {
                return ResourceManager.GetString("Weather_value_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain: heavy intensity.
        /// </summary>
        internal static string Weather_value_65 {
            get {
                return ResourceManager.GetString("Weather_value_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Rain: light.
        /// </summary>
        internal static string Weather_value_66 {
            get {
                return ResourceManager.GetString("Weather_value_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing Rain: heavy intensity.
        /// </summary>
        internal static string Weather_value_67 {
            get {
                return ResourceManager.GetString("Weather_value_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow fall: slight.
        /// </summary>
        internal static string Weather_value_71 {
            get {
                return ResourceManager.GetString("Weather_value_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow fall: moderate.
        /// </summary>
        internal static string Weather_value_73 {
            get {
                return ResourceManager.GetString("Weather_value_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow fall: heavy intensity.
        /// </summary>
        internal static string Weather_value_75 {
            get {
                return ResourceManager.GetString("Weather_value_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow grains.
        /// </summary>
        internal static string Weather_value_77 {
            get {
                return ResourceManager.GetString("Weather_value_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers: slight.
        /// </summary>
        internal static string Weather_value_80 {
            get {
                return ResourceManager.GetString("Weather_value_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers: moderate.
        /// </summary>
        internal static string Weather_value_81 {
            get {
                return ResourceManager.GetString("Weather_value_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers: violent.
        /// </summary>
        internal static string Weather_value_82 {
            get {
                return ResourceManager.GetString("Weather_value_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers: slight.
        /// </summary>
        internal static string Weather_value_85 {
            get {
                return ResourceManager.GetString("Weather_value_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers: heavy.
        /// </summary>
        internal static string Weather_value_86 {
            get {
                return ResourceManager.GetString("Weather_value_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        internal static string Weather_value_95 {
            get {
                return ResourceManager.GetString("Weather_value_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with slight hail.
        /// </summary>
        internal static string Weather_value_96 {
            get {
                return ResourceManager.GetString("Weather_value_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with heavy hail.
        /// </summary>
        internal static string Weather_value_99 {
            get {
                return ResourceManager.GetString("Weather_value_99", resourceCulture);
            }
        }
    }
}
